### ISSUE TITLE
(application crash) Get offline map

### ISSUE THREAD

**Issue by yutsuku** [openbmap/android#221]
What steps will reproduce the problem?

Go to Settings > Map
Click Get offline map

What is the expected output? What do you see instead?

Some sort list of regions to download the map for (Region > Country > State), instead application crashes at this step. 

What version are you using? On what operating system?

0.8.18 from f-droid on Android 7.1.2 (lineageos 14.1)

**Comment by 532910** [comment]
```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.openbmap, PID: 11843
E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.openbmap.activities.z.a' on a null object reference
E AndroidRuntime:       at org.openbmap.activities.aa.getGroupView(Unknown Source:21)
E AndroidRuntime:       at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
E AndroidRuntime:       at android.widget.AbsListView.obtainView(AbsListView.java:2365)
E AndroidRuntime:       at android.widget.ListView.measureHeightOfChildren(ListView.java:1408)
E AndroidRuntime:       at android.widget.ListView.onMeasure(ListView.java:1315)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
E AndroidRuntime:       at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1167)
E AndroidRuntime:       at android.widget.LinearLayout.onMeasure(LinearLayout.java:687)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:144)
E AndroidRuntime:       at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:69)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
E AndroidRuntime:       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E AndroidRuntime:       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
E AndroidRuntime:       at android.view.View.measure(View.java:22071)
E AndroidRuntime:       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
E AndroidRuntime:       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1477)
E AndroidRuntime:       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
E AndroidRuntime:       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
E AndroidRuntime:       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
E AndroidRuntime:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
E AndroidRuntime:       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
E AndroidRuntime:       at android.view.Choreographer.doFrame(Choreographer.java:658)
E AndroidRuntime:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
E AndroidRuntime:       at android.os.Handler.handleCallback(Handler.java:790)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:164)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:6494)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W ActivityManager:   Force finishing activity org.openbmap/.activities.SettingsActivity
I ActivityManager: Showing crash dialog for package org.openbmap u0
```
