### ISSUE TITLE
Export error; cannot upload collected data

### ISSUE THREAD

**Issue by gaya4** [openbmap/android#231]
What steps will reproduce the problem?
- Collect cell data
- Upload

What is the expected output? What do you see instead?
Upload successful, data deleted.

What version are you using? On what operating system?
Latest from F-DROID, 0.8.18, Android 4.4.4 Kitkat, custom rom "slimkat" since years on the same mobile, Samsung Galaxy Note 3.

Please provide any additional information below.
2 different behaviours I've observed.
1) With anonymous upload enabled:
Export error
Try again later. If problem persists, please file a bug at https://github.com/openbmap/android/issues
Side note:
In the german language file the link is different:
https://github.com/wish7code/openbmap/issues - this is how I got here, probably redirected.
2) with my default username and password that work fine on the website https://radiocells.org/
I get 
Export error
Incorrect username or password
I did mistype the credentials but copy and paste them to the website and radiobeacon app from a password manager (keepassx).
The issue persists since 2-3 months, but the issues popup from time to time and fix themselves after a month. But now I got more than 50000 objects to upload.

With the anonymous upload (1) the app says that it is uploading something. Error message pops up after the uploading and the data I have on the deivce doesn't get deleted. Not sure whether there was an actual upload. The latest upload was done at 23rd Feb 14:40 CET, 2-3 uploads were tried before.

With the credential bound upload (2) there is no actual upload but a few seconds after pressing the upload button the error appears. This stays in the foreground for some minutes and then the same message as (1) appears. If I OK the message and press upload again, the credentials error does not come up anymore, but the behaviour is like (1), exporting > uploading wifi files > error

Any debug etc that is needed? From the debugging menu I couldn't see something useful here.

**Comment by wish7code** [comment]
Thanks for reporting! There have been a couple of boot cycles over the weekend due to hardware replacements. Maybe some bad timing? Could you try again?

**Comment by gaya4** [comment]
Hello,
I tried with anonymous and non-anonymous, but there is no change. This error seemed to be there for me at least since 2 months; I would think you'd see that in the database incoming data if there were more users having that issue. Might be my device only.
If you need anything let me know!

**Comment by wish7code** [comment]
Proposal for work-around: if you activate Settings--> Skip upload as well as --> Keep local copy your scans are exported to the SD card. You may send this files to teams@radiocells... so we could import manually?

**Comment by yomgui** [comment]
Hi,

I have a similar experience than @gaya4, I was using the app, and suddenly the app stopped allowing upload. I was getting the message "Incorrect username or password".

Radiocell is installed on Android 4.4.2
- versionCode=27 targetSdk=23
- versionName=0.8.18
- installerPackageName=org.fdroid.fdroid

Here is part of the logcat:
```
E( 5984) I/O exception while checking credentials hostname in certificate didn't match: <radiocells.org> != <deguocun.de> OR <deguocun.de> OR <www.deguocun.de>  (e)
E( 5984) javax.net.ssl.SSLException: hostname in certificate didn't match: <radiocells.org> != <deguocun.de> OR <deguocun.de> OR <www.deguocun.de>  (e)
E( 5984)        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:185)  (e)
E( 5984)        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)  (e)
E( 5984)        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:114)  (e)
E( 5984)        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:95)  (e)
E( 5984)        at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)  (e)
E( 5984)        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)  (e)
E( 5984)        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)  (e)
E( 5984)        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)  (e)
E( 5984)        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)  (e)
E( 5984)        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:587)  (e)
E( 5984)        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:511)  (e)
E( 5984)        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:489)  (e)
E( 5984)        at org.openbmap.c.e.a(Unknown Source)  (e)
E( 5984)        at org.openbmap.c.e.a(Unknown Source)  (e)
E( 5984)        at org.openbmap.c.e.doInBackground(Unknown Source)  (e)
E( 5984)        at android.os.AsyncTask$2.call(AsyncTask.java:288)  (e)
E( 5984)        at java.util.concurrent.FutureTask.run(FutureTask.java:237)  (e)
E( 5984)        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)  (e)
E( 5984)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)  (e)
E( 5984)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)  (e)
E( 5984)        at java.lang.Thread.run(Thread.java:841)  (e)
E( 5984) Server reports bad user or password!  (bf)
E( 5984) Export session 306 failed  (StartscreenActivity)
```

Here is the list of certificates in my device:
```
        Issuer: C=US, O=thawte, Inc., OU=Certification Services Division, OU=(c) 2006 thawte, Inc. - For authorized use only, CN=thawte Primary Root CA
        Issuer: OU=Copyright (c) 1997 Microsoft Corp., OU=Microsoft Corporation, CN=Microsoft Root Authority
        Issuer: C=US, O=Wells Fargo WellsSecure, OU=Wells Fargo Bank NA, CN=WellsSecure Public Root Certificate Authority
        Issuer: C=TR, O=Elektronik Bilgi Guvenligi A.S., CN=e-Guven Kok Elektronik Sertifika Hizmet Saglayicisi
        Issuer: C=US, ST=Arizona, L=Scottsdale, O=Starfield Technologies, Inc., CN=Starfield Services Root Certificate Authority - G2
        Issuer: OU=GlobalSign Root CA - R2, O=GlobalSign, CN=GlobalSign
        Issuer: C=ES, L=C/ Muntaner 244 Barcelona, CN=Autoridad de Certificacion Firmaprofesional CIF A62634068/emailAddress=ca@firmaprofesional.com
        Issuer: emailAddress=pki@sk.ee, C=EE, O=AS Sertifitseerimiskeskus, CN=Juur-SK
        Issuer: C=DK, O=TDC, CN=TDC OCES CA
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Issuer: C=FR, O=Certplus, CN=Class 2 Primary CA
        Issuer: C=ES, ST=Madrid, L=Madrid, O=IPS Certification Authority s.l. ipsCA, OU=ipsCA, CN=ipsCA Global CA Root/emailAddress=global01@ipsca.com
        Issuer: C=US, O=Digital Signature Trust, OU=DST ACES, CN=DST ACES CA X6
        Issuer: C=ES, O=FNMT, OU=FNMT Clase 2 CA
        Issuer: C=TW, O=Government Root Certification Authority
        Issuer: C=DE, O=D-Trust GmbH, CN=D-TRUST Root Class 3 CA 2 2009
        Issuer: C=DE, O=TC TrustCenter GmbH, OU=TC TrustCenter Universal CA, CN=TC TrustCenter Universal CA III
        Issuer: C=DE, O=T-Systems Enterprise Services GmbH, OU=T-Systems Trust Center, CN=T-TeleSec GlobalRoot Class 3
        Issuer: OU=GlobalSign Root CA - R3, O=GlobalSign, CN=GlobalSign
        Issuer: C=EU, L=Madrid (see current address at www.camerfirma.com/address)/serialNumber=A82743287, O=AC Camerfirma S.A., CN=Chambers of Commerce Root - 2008
        Issuer: C=US, O=The Go Daddy Group, Inc., OU=Go Daddy Class 2 Certification Authority
        Issuer: C=US, O=Starfield Technologies, Inc., OU=Starfield Class 2 Certification Authority
        Issuer: C=US, O=GeoTrust Inc., OU=(c) 2007 GeoTrust Inc. - For authorized use only, CN=GeoTrust Primary Certification Authority - G2
        Issuer: C=DE, O=TC TrustCenter GmbH, OU=TC TrustCenter Class 2 CA, CN=TC TrustCenter Class 2 CA II
        Issuer: C=NO, O=Buypass AS-983163327, CN=Buypass Class 3 Root CA
        Issuer: C=KR, O=KISA, OU=Korea Certification Authority Central, CN=KISA RootCA 3
        Issuer: C=US, O=Network Solutions L.L.C., CN=Network Solutions Certificate Authority
        Issuer: C=US, O=America Online Inc., CN=America Online Root Certification Authority 2
        Issuer: C=IL, O=StartCom Ltd., OU=Secure Digital Certificate Signing, CN=StartCom Certification Authority
        Issuer: O=Cybertrust, Inc, CN=Cybertrust Global Root
        Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
        Issuer: C=CH, O=WISeKey, OU=Copyright (c) 2005, OU=OISTE Foundation Endorsed, CN=OISTE WISeKey Global Root GA CA
        Issuer: C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
        Issuer: C=SE, O=AddTrust AB, OU=AddTrust External TTP Network, CN=AddTrust External CA Root
        Issuer: C=CH, O=SwissSign AG, CN=SwissSign Gold CA - G2
        Issuer: CN=ACCVRAIZ1, OU=PKIACCV, O=ACCV, C=ES
        Issuer: C=NL, O=Staat der Nederlanden, CN=Staat der Nederlanden Root CA - G2
        Issuer: O=Entrust.net, OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU=(c) 1999 Entrust.net Limited, CN=Entrust.net Certification Authority (2048)
        Issuer: C=GR, O=Hellenic Academic and Research Institutions Cert. Authority, CN=Hellenic Academic and Research Institutions RootCA 2011
        Issuer: C=TR, L=Gebze - Kocaeli, O=T\xC3\xBCrkiye Bilimsel ve Teknolojik Ara\xC5\x9Ft\xC4\xB1rma Kurumu - T\xC3\x9CB\xC4\xB0TAK, OU=Ulusal Elektronik ve Kriptoloji Ara\xC5\x9Ft\xC4\xB1rma Enstit\xC3\xBCs\xC3\xBC - UEKAE, OU=Kamu Sertifikasyon Merkezi, CN=T\xC3\x9CB\xC4\xB0TAK UEKAE K\xC3\xB6k Sertifika Hizmet Sa\xC4\x9Flay\xC4\xB1c\xC4\xB1s\xC4\xB1 - S\xC3\xBCr\xC3\xBCm 3
        Issuer: C=ch, O=Swisscom, OU=Digital Certificate Services, CN=Swisscom Root CA 2
        Issuer: C=US, O=Entrust, Inc., OU=See www.entrust.net/legal-terms, OU=(c) 2009 Entrust, Inc. - for authorized use only, CN=Entrust Root Certification Authority - G2
        Issuer: C=CH, O=SwissSign AG, CN=SwissSign Platinum CA - G2
        Issuer: C=KR, O=KISA, OU=Korea Certification Authority Central, CN=KISA RootCA 1
        Issuer: C=ES, O=IZENPE S.A., CN=Izenpe.com
        Issuer: C=US, O=GTE Corporation, OU=GTE CyberTrust Solutions, Inc., CN=GTE CyberTrust Global Root
        Issuer: C=DE, O=Deutsche Telekom AG, OU=T-TeleSec Trust Center, CN=Deutsche Telekom Root CA 2
        Issuer: C=US, ST=UT, L=Salt Lake City, O=The USERTRUST Network, OU=http://www.usertrust.com, CN=UTN - DATACorp SGC
        Issuer: C=DE, O=TC TrustCenter GmbH, OU=TC TrustCenter Universal CA, CN=TC TrustCenter Universal CA I
        Issuer: C=CH, O=SwissSign AG, CN=SwissSign Silver CA - G2
        Issuer: C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2008 VeriSign, Inc. - For authorized use only, CN=VeriSign Universal Root Certification Authority
        Issuer: CN=T\xC3\x9CRKTRUST Elektronik Sertifika Hizmet Sa\xC4\x9Flay\xC4\xB1c\xC4\xB1s\xC4\xB1, C=TR, L=Ankara, O=T\xC3\x9CRKTRUST Bilgi \xC4\xB0leti\xC5\x9Fim ve Bili\xC5\x9Fim G\xC3\xBCvenli\xC4\x9Fi Hizmetleri A.\xC5\x9E. (c) Kas\xC4\xB1m 2005
        Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Global CA 2
        Issuer: C=FR, ST=France, L=Paris, O=PM/SGDN, OU=DCSSI, CN=IGC/A/emailAddress=igca@sgdn.pm.gouv.fr
        Issuer: C=US, O=Equifax, OU=Equifax Secure Certificate Authority
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO Certification Authority
        Issuer: C=HU, L=Budapest, O=NetLock Halozatbiztonsagi Kft., OU=Tanusitvanykiadok, CN=NetLock Uzleti (Class B) Tanusitvanykiado
        Issuer: C=BM, O=QuoVadis Limited, OU=Root Certification Authority, CN=QuoVadis Root Certification Authority
        Issuer: C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2007 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G4
        Issuer: C=HU, L=Budapest, O=NetLock Kft., OU=Tan\xC3\xBAs\xC3\xADtv\xC3\xA1nykiad\xC3\xB3k (Certification Services), CN=NetLock Arany (Class Gold) F\xC5\x91tan\xC3\xBAs\xC3\xADtv\xC3\xA1ny
        Issuer: C=HU, L=Budapest, O=NetLock Halozatbiztonsagi Kft., OU=Tanusitvanykiadok, CN=NetLock Expressz (Class C) Tanusitvanykiado
        Issuer: C=US, O=thawte, Inc., OU=Certification Services Division, OU=(c) 2008 thawte, Inc. - For authorized use only, CN=thawte Primary Root CA - G3
        Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Assured ID Root CA
        Issuer: C=US, O=Wells Fargo, OU=Wells Fargo Certification Authority, CN=Wells Fargo Root Certificate Authority
        Issuer: C=PL, O=Unizeto Sp. z o.o., CN=Certum CA
        Issuer: C=US, O=VISA, OU=Visa International Service Association, CN=Visa eCommerce Root
        Issuer: C=NO, O=Buypass AS-983163327, CN=Buypass Class 2 CA 1
        Issuer: C=US, O=VeriSign, Inc., OU=Class 3 Public Primary Certification Authority - G2, OU=(c) 1998 VeriSign, Inc. - For authorized use only, OU=VeriSign Trust Network
        Issuer: C=US, O=Equifax Secure Inc., CN=Equifax Secure Global eBusiness CA-1
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
        Issuer: C=US, O=VeriSign, Inc., OU=Class 3 Public Primary Certification Authority
        Issuer: C=US, OU=www.xrampsecurity.com, O=XRamp Security Services Inc, CN=XRamp Global Certification Authority
        Issuer: C=FR, O=Certinomis, OU=0002 433998903, CN=Certinomis - Autorit\xC3\xA9 Racine
        Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Global CA
        Issuer: C=DE, O=TC TrustCenter GmbH, OU=TC TrustCenter Class 3 CA, CN=TC TrustCenter Class 3 CA II
        Issuer: C=BM, O=QuoVadis Limited, CN=QuoVadis Root CA 2
        Issuer: L=ValiCert Validation Network, O=ValiCert, Inc., OU=ValiCert Class 3 Policy Validation Authority, CN=http://www.valicert.com//emailAddress=info@valicert.com
        Issuer: C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 1999 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G3
        Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert High Assurance EV Root CA
        Issuer: C=NO, O=Buypass AS-983163327, CN=Buypass Class 2 Root CA
        Issuer: O=RSA Security Inc, OU=RSA Security 2048 V3
        Issuer: CN=T\xC3\x9CRKTRUST Elektronik Sertifika Hizmet Sa\xC4\x9Flay\xC4\xB1c\xC4\xB1s\xC4\xB1, C=TR, L=ANKARA, O=(c) 2005 T\xC3\x9CRKTRUST Bilgi \xC4\xB0leti\xC5\x9Fim ve Bili\xC5\x9Fim G\xC3\xBCvenli\xC4\x9Fi Hizmetleri A.\xC5\x9E.
        Issuer: C=US, ST=Arizona, L=Scottsdale, O=Starfield Technologies, Inc., CN=Starfield Root Certificate Authority - G2
        Issuer: C=US, O=AffirmTrust, CN=AffirmTrust Networking
        Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Universal CA 2
        Issuer: C=RO, O=certSIGN, OU=certSIGN ROOT CA
        Issuer: C=CN, O=CNNIC, CN=CNNIC ROOT
        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO ECC Certification Authority
        Issuer: C=US, O=Equifax Secure, OU=Equifax Secure eBusiness CA-2
        Issuer: C=BM, O=QuoVadis Limited, CN=QuoVadis Root CA 3
        Issuer: C=PL, O=Unizeto Technologies S.A., OU=Certum Certification Authority, CN=Certum Trusted Network CA
        Issuer: C=HK, O=Hongkong Post, CN=Hongkong Post Root CA 1
        Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Primary Certification Authority
        Issuer: C=TW, O=Chunghwa Telecom Co., Ltd., OU=ePKI Root Certification Authority
        Issuer: C=JP, O=SECOM Trust Systems CO.,LTD., OU=Security Communication EV RootCA1
        Issuer: C=EU, L=Madrid (see current address at www.camerfirma.com/address)/serialNumber=A82743287, O=AC Camerfirma S.A., CN=Global Chambersign Root - 2008
        Issuer: C=EU, O=AC Camerfirma SA CIF A82743287, OU=http://www.chambersign.org, CN=Global Chambersign Root
        Issuer: C=US, O=Digital Signature Trust Co., OU=DSTCA E2
        Issuer: C=JP, O=SECOM Trust.net, OU=Security Communication RootCA1
        Issuer: C=FI, O=Sonera, CN=Sonera Class2 CA
        Issuer: C=US, O=thawte, Inc., OU=(c) 2007 thawte, Inc. - For authorized use only, CN=thawte Primary Root CA - G2
        Issuer: C=JP, O=Japan Certification Services, Inc., CN=SecureSign RootCA11
        Issuer: C=HU, ST=Hungary, L=Budapest, O=NetLock Halozatbiztonsagi Kft., OU=Tanusitvanykiadok, CN=NetLock Kozjegyzoi (Class A) Tanusitvanykiado
        Issuer: C=ES, O=Agencia Catalana de Certificacio (NIF Q-0801176-I), OU=Serveis Publics de Certificacio, OU=Vegeu https://www.catcert.net/verarrel (c)03, OU=Jerarquia Entitats de Certificacio Catalanes, CN=EC-ACC
        Issuer: C=BE, O=GlobalSign nv-sa, OU=Root CA, CN=GlobalSign Root CA
        Issuer: C=US, O=Entrust, Inc., OU=See www.entrust.net/legal-terms, OU=(c) 2012 Entrust, Inc. - for authorized use only, CN=Entrust Root Certification Authority - EC1
        Issuer: C=TW, O=TAIWAN-CA, OU=Root CA, CN=TWCA Root Certification Authority
        Issuer: C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
        Issuer: L=ValiCert Validation Network, O=ValiCert, Inc., OU=ValiCert Class 2 Policy Validation Authority, CN=http://www.valicert.com//emailAddress=info@valicert.com
        Issuer: C=US, O=America Online Inc., CN=America Online Root Certification Authority 1
        Issuer: C=US, O=SecureTrust Corporation, CN=Secure Global CA
        Issuer: C=US, O=Entrust, Inc., OU=www.entrust.net/CPS is incorporated by reference, OU=(c) 2006 Entrust, Inc., CN=Entrust Root Certification Authority
        Issuer: C=US, O=Digital Signature Trust Co., OU=DSTCA E1
        Issuer: C=ZA, ST=Western Cape, L=Cape Town, O=Thawte Consulting cc, OU=Certification Services Division, CN=Thawte Premium Server CA/emailAddress=premium-server@thawte.com
        Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=A-Trust-nQual-03, CN=A-Trust-nQual-03
        Issuer: C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 1999 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 4 Public Primary Certification Authority - G3
        Issuer: C=CN, O=China Mobile Communications Corp., CN=China Mobile Root CA2
        Issuer: C=US, O=GeoTrust Inc., OU=(c) 2008 GeoTrust Inc. - For authorized use only, CN=GeoTrust Primary Certification Authority - G3
        Issuer: C=CO, O=Sociedad Cameral de Certificaci\xC3\xB3n Digital - Certic\xC3\xA1mara S.A., CN=AC Ra\xC3\xADz Certic\xC3\xA1mara S.A.
        Issuer: C=US, O=AffirmTrust, CN=AffirmTrust Premium ECC
        Issuer: C=NL, O=Staat der Nederlanden, CN=Staat der Nederlanden Root CA
        Issuer: C=US, O=SecureTrust Corporation, CN=SecureTrust CA
        Issuer: C=ES, CN=Autoridad de Certificacion Firmaprofesional CIF A62634068
        Issuer: C=DK, O=TDC Internet, OU=TDC Internet Root CA
        Issuer: C=JP, O=SECOM Trust Systems CO.,LTD., OU=Security Communication RootCA2
        Issuer: C=SK, L=Bratislava, O=Disig a.s., CN=CA Disig
        Issuer: C=DE, O=D-Trust GmbH, CN=D-TRUST Root Class 3 CA 2 EV 2009
        Issuer: C=JP, O=Japan Certification Services, Inc., CN=SecureSign RootCA1
        Issuer: C=US, ST=UT, L=Salt Lake City, O=The USERTRUST Network, OU=http://www.usertrust.com, CN=UTN-USERFirst-Network Applications
        Issuer: C=US, O=AffirmTrust, CN=AffirmTrust Premium
        Issuer: C=ZA, ST=Western Cape, L=Cape Town, O=Thawte Consulting cc, OU=Certification Services Division, CN=Thawte Server CA/emailAddress=server-certs@thawte.com
        Issuer: C=US, O=AffirmTrust, CN=AffirmTrust Commercial
        Issuer: C=ch, O=Swisscom, OU=Digital Certificate Services, CN=Swisscom Root CA 1
        Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Universal CA
        Issuer: C=US, O=Equifax Secure Inc., CN=Equifax Secure eBusiness CA-1
        Issuer: C=HU, L=Budapest, O=Microsec Ltd., CN=Microsec e-Szigno Root CA 2009/emailAddress=info@e-szigno.hu
        Issuer: CN=ACEDICOM Root, OU=PKI, O=EDICOM, C=ES
        Issuer: C=NO, O=Buypass AS-983163327, CN=Buypass Class 3 CA 1
        Issuer: C=US, O=VeriSign, Inc., OU=Class 4 Public Primary Certification Authority - G2, OU=(c) 1998 VeriSign, Inc. - For authorized use only, OU=VeriSign Trust Network
        Issuer: C=US, O=Entrust.net, OU=www.entrust.net/CPS incorp. by ref. (limits liab.), OU=(c) 1999 Entrust.net Limited, CN=Entrust.net Secure Server Certification Authority
        Issuer: C=EU, O=AC Camerfirma SA CIF A82743287, OU=http://www.chambersign.org, CN=Chambers of Commerce Root
        Issuer: C=IL, O=StartCom Ltd., CN=StartCom Certification Authority G2
        Issuer: C=CN, O=China Mobile Communications Corp., CN=China Mobile CA
        Issuer: L=ValiCert Validation Network, O=ValiCert, Inc., OU=ValiCert Class 1 Policy Validation Authority, CN=http://www.valicert.com//emailAddress=info@valicert.com
        Issuer: CN=ComSign Secured CA, O=ComSign, C=IL
        Issuer: C=HU, L=Budapest, O=Microsec Ltd., OU=e-Szigno CA, CN=Microsec e-Szigno Root CA
        Issuer: CN=EBG Elektronik Sertifika Hizmet Sa\xC4\x9Flay\xC4\xB1c\xC4\xB1s\xC4\xB1, O=EBG Bili\xC5\x9Fim Teknolojileri ve Hizmetleri A.\xC5\x9E., C=TR
        Issuer: C=JP, O=Japanese Government, OU=ApplicationCA
        Issuer: C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
        Issuer: C=ES, O=Generalitat Valenciana, OU=PKIGVA, CN=Root CA Generalitat Valenciana
        Issuer: C=FR, O=Dhimyotis, CN=Certigna
        Issuer: C=US, ST=UT, L=Salt Lake City, O=The USERTRUST Network, OU=http://www.usertrust.com, CN=UTN-USERFirst-Hardware
```

**Comment by gaya4** [comment]
If it helps: With the same device as I have it, Samsung Galaxy Note 3 I went from Kitkat to Android Pie (9). After restoring all my data, I could upload just fine. Since the rom was not stable enough and I don't like the >Lollipop UI Navigation I decided to go back to Kitkat. The issue re-appeared again.

I will sooner or later have to go away from Kitkat and the issue would very likely disappear for me. So it seems to be an issue related to Kitkat. But I'm not sure; Since the app hasn't been updated for some time, the OS neither received anything I'm guessing the server might block some user agents that are uploading data.

**Comment by pietrodevo** [comment]
I am having the same issue on Galaxy S3 Neo with Android 4.4.2 and latest version (0.8.18).
Seems like @gaya4 pointed out about user agent getting blocked.
I would like to contribute to data collection too, an update for this app would be very appreciated!

**Comment by gaya4** [comment]
I'm now away from kitkat, a bit sad, but away anyways. The reported issue cannot be observed anymore.
