### ISSUE TITLE
 Turning off location permissions before adding a new session will cause RadioBeacon to crash

### ISSUE THREAD

**Issue by sjl872964789** [openbmap/android#249]
What steps will reproduce the problem?
1. Install and open RadioBeacon
2. Turn off location permission of RadioBeacon
3. Click on "New session"
4. Crash

What is the expected output? What do you see instead?
RadioBeacon should not crash

What version are you using? On what operating system?
Device: Galaxy A6s
OS: Android 7.1.2
Version: 0.8.18

Please provide any additional information below.
![ezgif com-video-to-gif (16)](https://user-images.githubusercontent.com/15941953/90969426-0183f100-e52b-11ea-9721-3da1385889fb.gif)

Logcat
```
08-23 10:24:03.355  6730  6730 E AndroidRuntime: FATAL EXCEPTION: main
08-23 10:24:03.355  6730  6730 E AndroidRuntime: Process: org.openbmap, PID: 6730
08-23 10:24:03.355  6730  6730 E AndroidRuntime: java.lang.RuntimeException: Unable to create service org.openbmap.services.wireless.WirelessLoggerService: java.lang.SecurityException: Neither user 10184 nor current process has android.permission.ACCESS_COARSE_LOCATION.
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.app.ActivityThread.-wrap4(Unknown Source:0)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6746)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-23 10:24:03.355  6730  6730 E AndroidRuntime: Caused by: java.lang.SecurityException: Neither user 10184 nor current process has android.permission.ACCESS_COARSE_LOCATION.
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2005)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1951)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:544)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.telephony.TelephonyManager.listen(TelephonyManager.java:3625)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at org.openbmap.services.wireless.WirelessLoggerService.e(Unknown Source:260)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at org.openbmap.services.wireless.WirelessLoggerService.onCreate(Unknown Source:143)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3522)
08-23 10:24:03.355  6730  6730 E AndroidRuntime:        ... 8 more
```

**Comment by sjl872964789** [comment]
Hi，any update about this issue？It would be really appreciated to get your concern on this.

**Comment by wish7code** [comment]
Hey there!

Unfortunately, this client has reached end of life...

But if you like to have a look at the beta version of the upcoming scanner app, drop me a private message at wish7code gmail.com

**Comment by JonnyTech** [comment]
Hey @wish7code 

Sorry for hijacking this thread but...

> Unfortunately, this client has reached end of life...

Is that why uploads have been failing this month?

> But if you like to have a look at the beta version of the upcoming scanner app, drop me a private message at wish7code gmail.com

Is this invitation open to all?

**Comment by wish7code** [comment]
> Is this invitation open to all?

Well, yes of course :-)

> Is that why uploads have been failing this month?

Sigh, this is probably related with serious network failures of our internet service provider.

**Comment by YYYSSSHHH** [comment]
Hey @wish7code, I know this client is outdated, but do you think the issue #249 is a bug?
